### ISSUE TITLE
5.1.3p1+ & Samsung Note 4: Eyes are misscrossed in build

### ISSUE THREAD

**Issue by zulman** [googlesamples/cardboard-unity#93]
Hi.

### What the problem?
All setting are default as in CardboardMain prefab
**Case 1** If i'm using Editor + Unity Remote with Note 4 everything is ok, picture is nicely focused in any Cardboard (2014 & 2015)
![Unity 5.2.1](http://gyazo.nivalnetwork.com/db/47b44cda1e9600c490da1c3d228354fb.png)

**Case 2** But after build for Note 4 (android 5.1.1) picture is deformatted (looks like eyes focus is wrong or like left eye picture is on right half of the screen and right eye picture on left side of the screen). Other devices are ok. 

### How it's looks like?

You can see that in build pictures are fullscreen, but via Unity Remote pictures are scaled down.

Build ![](http://i.imgur.com/L8JHkNp.jpg)
Editor via Unity Remote ![](http://i.imgur.com/mrC6jqN.png)

### How to reproduce it?
All setting are default as in CardboardMain prefab
Here is example project sources and build apk file
https://drive.google.com/folderview?id=0BzKVA--Bto53ZUhFTmd6UHF4OUE&usp=sharing

**Comment by smdol** [comment]
We have been getting reports that Unity 5.2 is returning different DPI values than Unity 5.1 does.  Can you try with Unity 5.1 to see if this is the same problem?

**Comment by zulman** [comment]
Same situation at Unity 5.1.3p3. Pictures are the same as in my first post. Is this bug successfully reproduced on your devices?

**Comment by zulman** [comment]
Checked Screen.dpi value.
- Unity 504f1 =527.
- Unity 521f1 =640
- Unity 513f1 =640

https://unity3d.com/unity/whats-new/unity-5.2.1 (IMPROVEMENTS section)
"Android: On some devices Screen.dpi returns more accurate values."

**Comment by smdol** [comment]
Ah, so the change in how DPI is reported started before 5.2, then.  This is going to be fixed in an upcoming SDK release:  we're going to get the DPI directly from Android (or iOS).  Unity's DPI value probably makes sense from a UI layout perspective, but we need the real DPI because we use it to figure out the actual physical screen size.

**Comment by zulman** [comment]
Looks like this, yep. So current latests compatible version with Cardboard plugin is 5.1.3p1. Any ETA about upcoming SDK release?

**Comment by smdol** [comment]
To answer your earlier question, yes we have started seeing this on devices here, after upgrading to recent versions of Unity. 

No, I'm not allowed to give dates on releases.

**Comment by zulman** [comment]
Got it. Sad situation for developers who are using something like Unity Networking (new in 5.2) and Cardboard :)

**Comment by zulman** [comment]
Pull request with temporary fix https://github.com/googlesamples/cardboard-unity/pull/94

**Comment by nathanmartz** [comment]
This should be fixed in the 0.6.0 SDK.

**Comment by ChrisDenham** [comment]
I am still getting this "crossed eyes" problem with some devices:
Motorola Moto X running Android 5.1
Sony Xperia Z3 Compact running Android 5.1.1

Seemed to work ok on:
Nexus 6P running Android 6.0

Anyone else still having problems with left and right images seeming to be crossed?

**Comment by ChrisDenham** [comment]
Also, even using the unity emulator, with screen size set to "nexus 5",  images look crossed to me, but ok when emulated screen size set to "nexus 6"
